version: '{branch}.{build}'
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2019
configuration: Release
init:
- ps: $branch = $env:APPVEYOR_REPO_BRANCH -replace '\W', '-'; $env:ASSEMBLY_INFORMATIONAL_VERSION = if ($branch -eq "master") { $env:APPVEYOR_BUILD_VERSION } else { "$env:APPVEYOR_BUILD_VERSION-$branch" }
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
nuget:
  account_feed: true
  project_feed: true
before_build:
- ps: cd src
- ps: nuget restore
build_script:
 - dotnet publish -c Release
artifacts:
- path: src\FMBot.Bot\bin\$(configuration)\netcoreapp3.0\publish
  name: BinaryRelease
- path: BinaryFiles
  name: BinaryFiles
deploy: on